server.port=${APP_PORT:8081}
spring.datasource.url=jdbc:postgresql://localhost:${DB_HOST_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# ?????? ??????????? ????????? ????
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis.cache=TRACE 
