spring.application.name=user-service

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.cache.type=redis

internal.api-key=${INTERNAL_API_KEY}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVICE_URL}/api/auth/.well-known/jwks.json

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always