server.port=${APP_PORT:8081}
spring.datasource.url=jdbc:postgresql://${DOCKER_DB_HOST}:${DB_HOST_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=${DOCKER_REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

