spring.application.name=user-service

# ------- Dadasourse ----------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ------- JPA ----------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ------- Liquibase ----------------
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true